./scripts/config --enable NET
./scripts/config --enable PACKET
./scripts/config --enable PACKET_DIAG
./scripts/config --enable UNIX
./scripts/config --enable UNIX_DIAG
./scripts/config --enable XFRM_USER
./scripts/config --disable XDP_SOCKETS
./scripts/config --enable INET
./scripts/config --enable IP_MULTICAST
./scripts/config --enable IP_ADVANCED_ROUTER
./scripts/config --enable IP_MROUTE
./scripts/config --enable IP_MROUTE_MULTIPLE_TABLES
./scripts/config --enable IP_PIMSM_V1
./scripts/config --enable IP_PIMSM_V2
./scripts/config --enable SYN_COOKIES
./scripts/config --enable INET_ESP
./scripts/config --enable INET_IPCOMP
./scripts/config --enable IP_SCTP
./scripts/config --enable BRIDGE
./scripts/config --enable NETFILTER
./scripts/config --enable IP_NF_IPTABLES
./scripts/config --enable IP_NF_NAT
./scripts/config --enable NETFILTER_ADVANCED
./scripts/config --enable NETFILTER_INGRESS
./scripts/config --enable NETFILTER_EGRESS
# enable if gentoo-kernel-bin enabled, disable for modules
./scripts/config --enable NF_CONNTRACK
./scripts/config --enable NF_CONNTRACK_MARK
#./scripts/config --enable NF_CONNTRACK_SECMARK
./scripts/config --enable NF_CONNTRACK_ZONES
./scripts/config --enable NF_CONNTRACK_PROCFS
./scripts/config --enable NF_CONNTRACK_EVENTS
./scripts/config --enable NF_CONNTRACK_TIMESTAMP
./scripts/config --enable NF_CONNTRACK_LABELS
#./scripts/config --enable NF_CONNTRACK_OVS
./scripts/config --enable IP_NF_MANGLE
./scripts/config --enable IP6_NF_MANGLE
./scripts/config --enable IP_MULTIPLE_TABLES
./scripts/config --enable NF_TABLES

./scripts/config --enable ETHTOOL_NETLINK

# eth drivers
./scripts/config --enable NETDEVICES
./scripts/config --enable NET_CORE
./scripts/config --enable ETHERNET
./scripts/config --disable NET_VENDOR_3COM
./scripts/config --disable NET_VENDOR_ADAPTEC
./scripts/config --disable NET_VENDOR_AGERE
./scripts/config --disable NET_VENDOR_ALACRITECH
./scripts/config --disable NET_VENDOR_ALTEON
./scripts/config --disable NET_VENDOR_AMAZON
./scripts/config --disable NET_VENDOR_AMD
./scripts/config --disable NET_VENDOR_AQUANTIA
./scripts/config --disable NET_VENDOR_ARC
./scripts/config --disable NET_VENDOR_ASIX
./scripts/config --disable NET_VENDOR_ATHEROS
./scripts/config --disable NET_VENDOR_BROADCOM
./scripts/config --disable NET_VENDOR_CADENCE
./scripts/config --disable NET_VENDOR_CAVIUM
./scripts/config --disable NET_VENDOR_CHELSIO
./scripts/config --disable NET_VENDOR_CISCO
./scripts/config --disable NET_VENDOR_CORTINA
./scripts/config --disable NET_VENDOR_DAVICOM
./scripts/config --disable NET_VENDOR_DEC
./scripts/config --disable NET_VENDOR_DLINK
./scripts/config --disable NET_VENDOR_EMULEX
./scripts/config --disable NET_VENDOR_ENGLEDER
./scripts/config --disable NET_VENDOR_EZCHIP
./scripts/config --disable NET_VENDOR_FUNGIBLE
./scripts/config --disable NET_VENDOR_GOOGLE
./scripts/config --disable NET_VENDOR_HUAWEI
./scripts/config --disable NET_VENDOR_JME
./scripts/config --disable NET_VENDOR_ADI
./scripts/config --disable NET_VENDOR_I825XX
./scripts/config --disable NET_VENDOR_LITEX
./scripts/config --disable NET_VENDOR_MARVELL
./scripts/config --disable NET_VENDOR_MELLANOX
./scripts/config --disable NET_VENDOR_META
./scripts/config --disable NET_VENDOR_MICREL
./scripts/config --disable NET_VENDOR_MICROCHIP
./scripts/config --disable NET_VENDOR_MICROSEMI
./scripts/config --disable NET_VENDOR_MICROSOFT
./scripts/config --disable NET_VENDOR_MYRI
./scripts/config --disable NET_VENDOR_NI
./scripts/config --disable NET_VENDOR_NATSEMI
./scripts/config --disable NET_VENDOR_NETERION
./scripts/config --disable NET_VENDOR_NETRONOME
./scripts/config --disable NET_VENDOR_8390
./scripts/config --disable NET_VENDOR_NVIDIA
./scripts/config --disable NET_VENDOR_OKI
./scripts/config --disable NET_VENDOR_PACKET_ENGINES
./scripts/config --disable NET_VENDOR_PENSANDO
./scripts/config --disable NET_VENDOR_QLOGIC
./scripts/config --disable NET_VENDOR_BROCADE
./scripts/config --disable NET_VENDOR_QUALCOMM
./scripts/config --disable NET_VENDOR_RDC
./scripts/config --disable NET_VENDOR_REALTEK
./scripts/config --disable NET_VENDOR_RENESAS
./scripts/config --disable NET_VENDOR_ROCKER
./scripts/config --disable NET_VENDOR_SAMSUNG
./scripts/config --disable NET_VENDOR_SEEQ
./scripts/config --disable NET_VENDOR_SILAN
./scripts/config --disable NET_VENDOR_SIS
./scripts/config --disable NET_VENDOR_SOLARFLARE
./scripts/config --disable NET_VENDOR_SMSC
./scripts/config --disable NET_VENDOR_SOCIONEXT
./scripts/config --disable NET_VENDOR_STMICRO
./scripts/config --disable NET_VENDOR_SUN
./scripts/config --disable NET_VENDOR_SYNOPSYS
./scripts/config --disable NET_VENDOR_TEHUTI
./scripts/config --disable NET_VENDOR_TI
./scripts/config --disable NET_VENDOR_VERTEXCOM
./scripts/config --disable NET_VENDOR_VIA
./scripts/config --disable NET_VENDOR_WANGXUN
./scripts/config --disable NET_VENDOR_WIZNET
./scripts/config --disable NET_VENDOR_XILINX
./scripts/config --enable NET_VENDOR_INTEL


# wifi
./scripts/config --enable WLAN
./scripts/config --module CFG80211
./scripts/config --disable CFG80211_DEBUGFS
./scripts/config --module MAC80211
./scripts/config --disable WLAN_VENDOR_ADMTEK
./scripts/config --disable WLAN_VENDOR_ATH
./scripts/config --disable WLAN_VENDOR_ATMEL
./scripts/config --disable WLAN_VENDOR_BROADCOM
./scripts/config --enable WLAN_VENDOR_INTEL
./scripts/config --disable IPW2100
./scripts/config --disable IPW2200
./scripts/config --disable IWL4965
./scripts/config --disable IWL3945
./scripts/config --module IWLWIFI
./scripts/config --disable IWLDVM
./scripts/config --module IWLMVM
./scripts/config --disable WLAN_VENDOR_INTERSIL
./scripts/config --disable WLAN_VENDOR_MARVELL
./scripts/config --disable WLAN_VENDOR_MEDIATEK
./scripts/config --disable WLAN_VENDOR_MICROCHIP
./scripts/config --disable WLAN_VENDOR_PURELIFI
./scripts/config --disable WLAN_VENDOR_RALINK
./scripts/config --disable WLAN_VENDOR_REALTEK
./scripts/config --disable WLAN_VENDOR_RSI
./scripts/config --disable WLAN_VENDOR_SILABS
./scripts/config --disable WLAN_VENDOR_ST
./scripts/config --disable WLAN_VENDOR_TI
./scripts/config --disable WLAN_VENDOR_ZYDAS
./scripts/config --disable WLAN_VENDOR_QUANTENNA
./scripts/config --disable MAC80211_HWSIM
./scripts/config --disable USB_NET_RNDIS_WLAN
./scripts/config --disable VIRT_WIFI

# required by iwd
./scripts/config --enable CRYPTO_USER_API_HASH
./scripts/config --enable KEY_DH_OPERATIONS
./scripts/config --enable CRYPTO_MD5
./scripts/config --enable CRYPTO_HMAC
./scripts/config --enable CRYPTO_USER_API_SKCIPHER
./scripts/config --enable CRYPTO_ECB
./scripts/config --enable CRYPTO_CBC
./scripts/config --enable CRYPTO_DES
./scripts/config --enable CRYPTO_AES
./scripts/config --enable CRYPTO_AES_NI_INTEL
./scripts/config --enable CRYPTO_DES3_EDE_X86_64

# wireguard
./scripts/config --enable WIREGUARD
./scripts/config --enable IPV6_MULTIPLE_TABLES
./scripts/config --enable NETFILTER_XT_MARK
./scripts/config --enable NETFILTER_XT_CONNMARK
./scripts/config --enable NETFILTER_XT_MATCH_COMMENT
./scripts/config --enable IP6_NF_IPTABLES   # required by IP6_NF_RAW
./scripts/config --enable IP6_NF_RAW
./scripts/config --enable IP_NF_RAW
./scripts/config --enable IP6_NF_FILTER

# wireless-regdb-20250220 reports:
# * You can safely disable CFG80211_CRDA_SUPPORT
./scripts/config --disable CFG80211_CRDA_SUPPORT
