./scripts/config --enable SOUND
./scripts/config --enable SND
./scripts/config --enable SND_SOC
./scripts/config --enable SND_SOC_SOF_TIGERLAKE
./scripts/config --enable SND_SOC_INTEL_MACH
./scripts/config --enable SND_SOC_INTEL_USER_FRIENDLY_LONG_NAMES
./scripts/config --enable SND_SOC_INTEL_SKL_HDA_DSP_GENERIC_MACH
./scripts/config --enable SND_OSSEMUL
./scripts/config --enable SND_MIXER_OSS
./scripts/config --enable SND_PCM_OSS
./scripts/config --enable SND_HRTIMER
./scripts/config --enable SND_SEQUENCER
./scripts/config --enable SND_SEQ_DUMMY
./scripts/config --enable SND_SEQUENCER_OSS
./scripts/config --enable SND_SEQ_HRTIMER_DEFAULT
./scripts/config --disable SND_DRIVERS
./scripts/config --enable SND_PCI
./scripts/config --disable SND_AD1889
./scripts/config --disable SND_ALS300
./scripts/config --disable SND_ALS4000
./scripts/config --disable SND_ALI5451
./scripts/config --disable SND_ASIHPI
./scripts/config --disable SND_ATIIXP
./scripts/config --disable SND_ATIIXP_MODEM
./scripts/config --disable SND_AU8810
./scripts/config --disable SND_AU8820
./scripts/config --disable SND_AU8830
./scripts/config --disable SND_AZT3328
./scripts/config --disable SND_BT87X
./scripts/config --disable SND_CA0106
./scripts/config --disable SND_CMIPCI
./scripts/config --disable SND_OXYGEN_LIB
./scripts/config --disable SND_OXYGEN
./scripts/config --disable SND_CS4281
./scripts/config --disable SND_CS46XX
./scripts/config --disable SND_CS46XX_NEW_DSP
./scripts/config --disable SND_CTXFI
./scripts/config --disable SND_DARLA20
./scripts/config --disable SND_GINA20
./scripts/config --disable SND_LAYLA20
./scripts/config --disable SND_DARLA24
./scripts/config --disable SND_GINA24
./scripts/config --disable SND_LAYLA24
./scripts/config --disable SND_MONA
./scripts/config --disable SND_MIA
./scripts/config --disable SND_ECHO3G
./scripts/config --disable SND_INDIGO
./scripts/config --disable SND_INDIGOIO
./scripts/config --disable SND_INDIGODJ
./scripts/config --disable SND_INDIGOIOX
./scripts/config --disable SND_INDIGODJX
./scripts/config --disable SND_EMU10K1
./scripts/config --disable SND_EMU10K1_SEQ
./scripts/config --disable SND_EMU10K1X
./scripts/config --disable SND_ENS1370
./scripts/config --disable SND_ENS1371
./scripts/config --disable SND_ES1938
./scripts/config --disable SND_ES1968
./scripts/config --disable SND_ES1968_INPUT
./scripts/config --disable SND_ES1968_RADIO
./scripts/config --disable SND_FM801
./scripts/config --disable SND_FM801_TEA575X_BOOL
./scripts/config --disable SND_HDSP
./scripts/config --disable SND_HDSPM
./scripts/config --disable SND_ICE1712
./scripts/config --disable SND_ICE1724
./scripts/config --disable SND_INTEL8X0
./scripts/config --disable SND_INTEL8X0M
./scripts/config --disable SND_KORG1212
./scripts/config --disable SND_LOLA
./scripts/config --disable SND_LX6464ES
./scripts/config --disable SND_MAESTRO3
./scripts/config --disable SND_MAESTRO3_INPUT
./scripts/config --disable SND_MIXART
./scripts/config --disable SND_NM256
./scripts/config --disable SND_PCXHR
./scripts/config --disable SND_RIPTIDE
./scripts/config --disable SND_RME32
./scripts/config --disable SND_RME96
./scripts/config --disable SND_RME9652
./scripts/config --disable SND_SONICVIBES
./scripts/config --disable SND_TRIDENT
./scripts/config --disable SND_VIA82XX
./scripts/config --disable SND_VIA82XX_MODEM
./scripts/config --disable SND_VIRTUOSO
./scripts/config --disable SND_VX222
./scripts/config --disable SND_YMFPCI
./scripts/config --disable SND_HDA_INTEL
./scripts/config --enable SND_HDA_HWDEP
./scripts/config --enable SND_HDA_RECONFIG
./scripts/config --enable SND_HDA_INPUT_BEEP
./scripts/config --enable SND_HDA_PATCH_LOADER
./scripts/config --enable SND_HDA_CODEC_REALTEK
./scripts/config --disable SND_HDA_CODEC_ANALOG
./scripts/config --disable SND_HDA_CODEC_SIGMATEL
./scripts/config --disable SND_HDA_CODEC_VIA
./scripts/config --enable SND_HDA_CODEC_HDMI
./scripts/config --disable SND_HDA_CODEC_CIRRUS
./scripts/config --disable SND_HDA_CODEC_CONEXANT
./scripts/config --disable SND_HDA_CODEC_CA0110
./scripts/config --disable SND_HDA_CODEC_CA0132
./scripts/config --disable SND_HDA_CODEC_CA0132_DSP
./scripts/config --disable SND_HDA_CODEC_CMEDIA
./scripts/config --disable SND_HDA_CODEC_SI3054
./scripts/config --disable SND_USB
./scripts/config --disable SND_FIREWIRE
./scripts/config --enable SND_SOC
./scripts/config --disable SND_SOC_AMD_ACP
./scripts/config --disable SND_SOC_AMD_ACP3x
./scripts/config --disable SND_SOC_AMD_RENOIR
./scripts/config --disable SND_AMD_ACP_CONFIG
./scripts/config --disable SND_I2S_HI6210_I2S
./scripts/config --enable SND_SOC_INTEL_SST_TOPLEVEL
./scripts/config --disable SND_SST_ATOM_HIFI2_PLATFORM_ACPI
./scripts/config --enable COMMON_CLK
./scripts/config --disable SND_SOC_INTEL_APL
./scripts/config --disable SND_SOC_INTEL_KBL
./scripts/config --disable SND_SOC_INTEL_GLK
./scripts/config --disable SND_SOC_INTEL_CNL
./scripts/config --disable SND_SOC_INTEL_CFL
./scripts/config --disable SND_SOC_INTEL_CML_H
./scripts/config --disable SND_SOC_INTEL_CML_LP
./scripts/config --disable SND_SOC_INTEL_SKL_RT286_MACH
./scripts/config --disable SND_SOC_INTEL_SKL_NAU88L25_SSM4567_MACH
./scripts/config --disable SND_SOC_INTEL_SKL_NAU88L25_MAX98357A_MACH
./scripts/config --disable SND_SOC_INTEL_SOF_RT5682_MACH
./scripts/config --enable SND_SOC_SOF_TOPLEVEL
./scripts/config --enable SND_SOC_SOF_PCI
./scripts/config --enable SND_SOC_SOF_ACPI
./scripts/config --disable SND_SOC_SOF_AMD_TOPLEVEL
./scripts/config --enable SND_SOC_SOF_INTEL_TOPLEVEL
./scripts/config --disable SND_SOC_SOF_BAYTRAIL
./scripts/config --disable SND_SOC_SOF_BROADWELL
./scripts/config --disable SND_SOC_SOF_MERRIFIELD
./scripts/config --disable SND_SOC_SOF_SKYLAKE
./scripts/config --disable SND_SOC_SOF_KABYLAKE
./scripts/config --disable SND_SOC_SOF_APOLLOLAKE
./scripts/config --disable SND_SOC_SOF_GEMINILAKE
./scripts/config --disable SND_SOC_SOF_CANNONLAKE
./scripts/config --disable SND_SOC_SOF_COFFEELAKE
./scripts/config --disable SND_SOC_SOF_COMETLAKE
./scripts/config --disable SND_SOC_SOF_ICELAKE
./scripts/config --disable SND_SOC_SOF_JASPERLAKE
./scripts/config --disable SND_SOC_SOF_ELKHARTLAKE
./scripts/config --disable SND_SOC_SOF_ALDERLAKE
./scripts/config --disable SND_SOC_SOF_METEORLAKE
./scripts/config --disable SND_SOC_SOF_LUNARLAKE
./scripts/config --disable SND_SOC_SOF_PANTHERLAKE
./scripts/config --enable SND_SOC_SOF_HDA_LINK
./scripts/config --enable SND_SOC_SOF_HDA_AUDIO_CODEC
./scripts/config --disable SND_SOC_SOF_INTEL_SOUNDWIRE
./scripts/config --disable SND_SOC_AC97_CODEC
./scripts/config --disable SND_SOC_ADAU_UTILS
./scripts/config --disable SND_SOC_ADAU1372_I2C
./scripts/config --disable SND_SOC_ADAU1372_SPI
./scripts/config --disable SND_SOC_ADAU1701
./scripts/config --disable SND_SOC_ADAU17X1
./scripts/config --disable SND_SOC_ADAU1761
./scripts/config --disable SND_SOC_ADAU1761_I2C
./scripts/config --disable SND_SOC_ADAU1761_SPI
./scripts/config --disable SND_SOC_ADAU7002
./scripts/config --disable SND_SOC_ADAU7118_HW
./scripts/config --disable SND_SOC_ADAU7118_I2C
./scripts/config --disable SND_SOC_AK4104
./scripts/config --disable SND_SOC_AK4118
./scripts/config --disable SND_SOC_AK4375
./scripts/config --disable SND_SOC_AK4458
./scripts/config --disable SND_SOC_AK4554
./scripts/config --disable SND_SOC_AK4613
./scripts/config --disable SND_SOC_AK4642
./scripts/config --disable SND_SOC_AK5386
./scripts/config --disable SND_SOC_AK5558
./scripts/config --disable SND_SOC_ALC5623
./scripts/config --disable SND_SOC_AW8738
./scripts/config --disable SND_SOC_BD28623
./scripts/config --disable SND_SOC_BT_SCO
./scripts/config --disable SND_SOC_CS35L32
./scripts/config --disable SND_SOC_CS35L33
./scripts/config --disable SND_SOC_CS35L34
./scripts/config --disable SND_SOC_CS35L35
./scripts/config --disable SND_SOC_CS35L36
./scripts/config --disable SND_SOC_CS35L41_SPI
./scripts/config --disable SND_SOC_CS35L41_I2C
./scripts/config --disable SND_SOC_CS35L45_SPI
./scripts/config --disable SND_SOC_CS35L45_I2C
./scripts/config --disable SND_SOC_CS42L42_CORE
./scripts/config --disable SND_SOC_CS42L42
./scripts/config --disable SND_SOC_CS42L51_I2C
./scripts/config --disable SND_SOC_CS42L52
./scripts/config --disable SND_SOC_CS42L56
./scripts/config --disable SND_SOC_CS42L73
./scripts/config --disable SND_SOC_CS42L83
./scripts/config --disable SND_SOC_CS4234
./scripts/config --disable SND_SOC_CS4265
./scripts/config --disable SND_SOC_CS4270
./scripts/config --disable SND_SOC_CS4271_I2C
./scripts/config --disable SND_SOC_CS4271_SPI
./scripts/config --disable SND_SOC_CS42XX8_I2C
./scripts/config --disable SND_SOC_CS43130
./scripts/config --disable SND_SOC_CS4341
./scripts/config --disable SND_SOC_CS4349
./scripts/config --disable SND_SOC_CS53L30
./scripts/config --disable SND_SOC_CX2072X
./scripts/config --disable SND_SOC_DA7213
./scripts/config --enable SND_SOC_DMIC
./scripts/config --disable SND_SOC_ES7134
./scripts/config --disable SND_SOC_ES7241
./scripts/config --disable SND_SOC_ES8316
./scripts/config --disable SND_SOC_ES8326
./scripts/config --disable SND_SOC_ES8328
./scripts/config --disable SND_SOC_ES8328_I2C
./scripts/config --disable SND_SOC_ES8328_SPI
./scripts/config --disable SND_SOC_GTM601
./scripts/config --enable SND_SOC_HDAC_HDA
./scripts/config --enable SND_SOC_HDA
./scripts/config --disable SND_SOC_ICS43432
./scripts/config --disable SND_SOC_INNO_RK3036
./scripts/config --disable SND_SOC_MAX98088
./scripts/config --enable SND_SOC_MAX98357A
./scripts/config --disable SND_SOC_MAX98504
./scripts/config --disable SND_SOC_MAX9867
./scripts/config --disable SND_SOC_MAX98927
./scripts/config --disable SND_SOC_MAX98520
./scripts/config --enable SND_SOC_MAX98373_I2C
./scripts/config --disable SND_SOC_MAX98373_SDW
./scripts/config --enable SND_SOC_MAX98390
./scripts/config --disable SND_SOC_MAX98396
./scripts/config --disable SND_SOC_MAX9860
./scripts/config --disable SND_SOC_MSM8916_WCD_DIGITAL
./scripts/config --disable SND_SOC_PCM1681
./scripts/config --disable SND_SOC_PCM1789
./scripts/config --disable SND_SOC_PCM1789_I2C
./scripts/config --disable SND_SOC_PCM179X_I2C
./scripts/config --disable SND_SOC_PCM179X_SPI
./scripts/config --disable SND_SOC_PCM186X
./scripts/config --disable SND_SOC_PCM186X_I2C
./scripts/config --disable SND_SOC_PCM186X_SPI
./scripts/config --disable SND_SOC_PCM3060
./scripts/config --disable SND_SOC_PCM3060_I2C
./scripts/config --disable SND_SOC_PCM3060_SPI
./scripts/config --disable SND_SOC_PCM3168A_I2C
./scripts/config --disable SND_SOC_PCM3168A_SPI
./scripts/config --disable SND_SOC_PCM5102A
./scripts/config --disable SND_SOC_PCM512x_I2C
./scripts/config --disable SND_SOC_PCM512x_SPI
./scripts/config --disable SND_SOC_RK3328
./scripts/config --disable SND_SOC_RL6231
./scripts/config --disable SND_SOC_RT1308_SDW
./scripts/config --disable SND_SOC_RT1316_SDW
./scripts/config --disable SND_SOC_RT1318_SDW
./scripts/config --disable SND_SOC_RT5616
./scripts/config --disable SND_SOC_RT5631
./scripts/config --disable SND_SOC_RT5640
./scripts/config --disable SND_SOC_RT5659
./scripts/config --disable SND_SOC_RT5682
./scripts/config --disable SND_SOC_RT5682_SDW
./scripts/config --disable SND_SOC_RT700
./scripts/config --disable SND_SOC_RT700_SDW
./scripts/config --disable SND_SOC_RT711
./scripts/config --disable SND_SOC_RT711_SDW
./scripts/config --disable SND_SOC_RT711_SDCA_SDW
./scripts/config --disable SND_SOC_RT715
./scripts/config --disable SND_SOC_RT715_SDW
./scripts/config --disable SND_SOC_RT715_SDCA_SDW
./scripts/config --disable SND_SOC_RT9120
./scripts/config --disable SND_SOC_SGTL5000
./scripts/config --disable SND_SOC_SIGMADSP
./scripts/config --disable SND_SOC_SIGMADSP_REGMAP
./scripts/config --disable SND_SOC_SIMPLE_AMPLIFIER
./scripts/config --disable SND_SOC_SIMPLE_MUX
./scripts/config --disable SND_SOC_SPDIF
./scripts/config --disable SND_SOC_SRC4XXX_I2C
./scripts/config --disable SND_SOC_SSM2305
./scripts/config --disable SND_SOC_SSM2518
./scripts/config --disable SND_SOC_SSM2602_SPI
./scripts/config --disable SND_SOC_SSM2602_I2C
./scripts/config --enable SND_SOC_SSM4567
./scripts/config --disable SND_SOC_STA32X
./scripts/config --disable SND_SOC_STA350
./scripts/config --disable SND_SOC_STI_SAS
./scripts/config --disable SND_SOC_TAS2552
./scripts/config --disable SND_SOC_TAS2562
./scripts/config --disable SND_SOC_TAS2764
./scripts/config --disable SND_SOC_TAS2770
./scripts/config --disable SND_SOC_TAS2780
./scripts/config --disable SND_SOC_TAS5086
./scripts/config --disable SND_SOC_TAS571X
./scripts/config --disable SND_SOC_TAS5720
./scripts/config --disable SND_SOC_TAS5805M
./scripts/config --disable SND_SOC_TAS6424
./scripts/config --disable SND_SOC_TDA7419
./scripts/config --disable SND_SOC_TFA9879
./scripts/config --disable SND_SOC_TFA989X
./scripts/config --disable SND_SOC_TLV320ADC3XXX
./scripts/config --disable SND_SOC_TLV320AIC23_I2C
./scripts/config --disable SND_SOC_TLV320AIC23_SPI
./scripts/config --disable SND_SOC_TLV320AIC31XX
./scripts/config --disable SND_SOC_TLV320AIC32X4
./scripts/config --disable SND_SOC_TLV320AIC32X4_I2C
./scripts/config --disable SND_SOC_TLV320AIC32X4_SPI
./scripts/config --disable SND_SOC_TLV320AIC3X_I2C
./scripts/config --disable SND_SOC_TLV320AIC3X_SPI
./scripts/config --disable SND_SOC_TLV320ADCX140
./scripts/config --disable SND_SOC_TS3A227E
./scripts/config --disable SND_SOC_TSCS42XX
./scripts/config --disable SND_SOC_TSCS454
./scripts/config --disable SND_SOC_UDA1334
./scripts/config --disable SND_SOC_WCD938X_SDW
./scripts/config --disable SND_SOC_WM8510
./scripts/config --disable SND_SOC_WM8523
./scripts/config --disable SND_SOC_WM8524
./scripts/config --disable SND_SOC_WM8580
./scripts/config --disable SND_SOC_WM8711
./scripts/config --disable SND_SOC_WM8728
./scripts/config --disable SND_SOC_WM8731_I2C
./scripts/config --disable SND_SOC_WM8731_SPI
./scripts/config --disable SND_SOC_WM8737
./scripts/config --disable SND_SOC_WM8741
./scripts/config --disable SND_SOC_WM8750
./scripts/config --disable SND_SOC_WM8753
./scripts/config --disable SND_SOC_WM8770
./scripts/config --disable SND_SOC_WM8776
./scripts/config --disable SND_SOC_WM8782
./scripts/config --disable SND_SOC_WM8804_I2C
./scripts/config --disable SND_SOC_WM8804_SPI
./scripts/config --disable SND_SOC_WM8903
./scripts/config --disable SND_SOC_WM8904
./scripts/config --disable SND_SOC_WM8940
./scripts/config --disable SND_SOC_WM8960
./scripts/config --disable SND_SOC_WM8962
./scripts/config --disable SND_SOC_WM8974
./scripts/config --disable SND_SOC_WM8978
./scripts/config --disable SND_SOC_WM8985
./scripts/config --disable SND_SOC_WSA881X
./scripts/config --disable SND_SOC_WSA883X
./scripts/config --disable SND_SOC_ZL38060
./scripts/config --disable SND_SOC_MAX9759
./scripts/config --disable SND_SOC_MT6351
./scripts/config --disable SND_SOC_MT6358
./scripts/config --disable SND_SOC_MT6660
./scripts/config --disable SND_SOC_NAU8315
./scripts/config --disable SND_SOC_NAU8540
./scripts/config --disable SND_SOC_NAU8810
./scripts/config --disable SND_SOC_NAU8821
./scripts/config --disable SND_SOC_NAU8822
./scripts/config --disable SND_SOC_NAU8824
./scripts/config --disable SND_SOC_NAU8825
./scripts/config --disable SND_SOC_TPA6130A2
./scripts/config --disable SND_SOC_LPASS_WSA_MACRO
./scripts/config --disable SND_SOC_LPASS_VA_MACRO
./scripts/config --disable SND_SOC_LPASS_RX_MACRO
./scripts/config --disable SND_SOC_LPASS_TX_MACRO
./scripts/config --disable SND_SIMPLE_CARD
./scripts/config --disable SND_SOC_INTEL_KEEMBAY

./scripts/config --set-val SND_HDA_PREALLOC_SIZE 2048
./scripts/config --disable SND_SPI
