# generated by such step:
# 1, boot into 6.12.25-gentoo-dist (gentoo-kernel-bin)
# 2. lsmod | awk '{print $1;}' | while read mod ; do module_to_config $mod ; done  > /tmp/current_mod
# 3. su - root; 
# 4. cd /usr/src/linux/  ; grep CONFIG_ /tmp/current_mod |  while read CO; do grep^C$CO=" .config || echo ./script/config --enable ${CO#CONFIG_} >&3 ; done 3>/tmp/15_from_localmod.sh
# 5. sh /tmp/15_from_localmod.sh
# 6. make olddefconfig
# 7. check_config /tmp/15_from_localmod.sh | grep should
# 8. resolve all unsatisfied config
# 9. remove unneccessary module 

./scripts/config --enable IP6_NF_NAT
./scripts/config --enable NETFILTER_XT_SET
./scripts/config --enable IP_SET
./scripts/config --enable USB_NET_CDC_NCM
./scripts/config --enable USB_NET_CDCETHER
./scripts/config --enable USB_USBNET
./scripts/config --enable MII
./scripts/config --enable USB_IPHETH
./scripts/config --enable APPLE_MFI_FASTCHARGE
./scripts/config --enable INPUT_UINPUT
./scripts/config --enable UHID
./scripts/config --enable CRYPTO_DES3_EDE_X86_64
./scripts/config --enable CRYPTO_DES
./scripts/config --enable CRYPTO_LIB_DES
./scripts/config --enable CRYPTO_MD4
./scripts/config --enable VLAN_8021Q_GVRP   # required by GARP
./scripts/config --enable GARP
./scripts/config --enable VLAN_8021Q_MVRP   # required by MRP
./scripts/config --enable MRP
#./scripts/config --module DRM_XE
#./scripts/config --module DRM_GPUVM
#./scripts/config --module DRM_SCHED
#./scripts/config --module DRM_SUBALLOC_HELPER
#./scripts/config --module DRM_TTM_HELPER
#./scripts/config --module DRM_EXEC
./scripts/config --enable INTEL_UNCORE_FREQ_CONTROL
./scripts/config --enable INTEL_UNCORE_FREQ_CONTROL
./scripts/config --enable INTEL_TCC_COOLING
./scripts/config --enable SOUNDWIRE_INTEL
./scripts/config --enable SOUNDWIRE_CADENCE
#./scripts/config --enable USB_VIDEO_CLASS
#./scripts/config --enable BT_RTL
#./scripts/config --enable UVC_COMMON
#./scripts/config --enable BT_BCM
#./scripts/config --enable VIDEOBUF2_VMALLOC
#./scripts/config --enable VIDEOBUF2_MEMOPS
#./scripts/config --enable BT_MTK
#./scripts/config --enable VIDEOBUF2_V4L2
#/./scripts/config --enable VIDEOBUF2_CORE
# ./scripts/config --enable VIDEO_DEV  ???
./scripts/config --enable SOUNDWIRE_GENERIC_ALLOCATION
./scripts/config --enable SOUNDWIRE
./scripts/config --enable MEDIA_SUPPORT
#./scripts/config --enable SND_SOC_INTEL_AVS
./scripts/config --enable SND_SOC_HDA
./scripts/config --enable INTEL_POWERCLAMP
./scripts/config --enable SENSORS_CORETEMP
#./scripts/config --enable AC97_BUS
#./scripts/config --enable SND_DMAENGINE_PCM
#./scripts/config --enable INT340X_THERMAL
#./scripts/config --enable INTEL_MEI_PXP
#./scripts/config --enable INTEL_MEI_HDCP
./scripts/config --enable MTD_SPI_NOR
./scripts/config --enable MTD
./scripts/config --enable INTEL_RAPL
#./scripts/config --enable PROC_THERMAL_MMIO_RAPL
./scripts/config --enable INTEL_RAPL_CORE
#./scripts/config --enable SPI_INTEL_PCI
#./scripts/config --enable I2C_I801
#./scripts/config --enable SPI_INTEL
./scripts/config --enable INTEL_IDMA64
#./scripts/config --enable CEC_CORE
#./scripts/config --enable INTEL_SOC_DTS_IOSF_CORE
./scripts/config --enable INTEL_PMC_CORE
#./scripts/config --enable ACPI_THERMAL_REL
./scripts/config --enable INTEL_VSEC
./scripts/config --enable INTEL_PMT_TELEMETRY
./scripts/config --enable INTEL_PMT_CLASS
./scripts/config --enable ACPI_PROCESSOR_AGGREGATOR
./scripts/config --enable INPUT_SPARSEKMAP
./scripts/config --enable BLK_DEV_LOOP
./scripts/config --enable NETFILTER_NETLINK
./scripts/config --enable CRC_T10DIF
./scripts/config --enable CRYPTO_CRCT10DIF_PCLMUL
./scripts/config --enable CRYPTO_CRC32_PCLMUL
./scripts/config --enable CRYPTO_CRC32C_INTEL
./scripts/config --enable CRYPTO_POLYVAL_CLMUL_NI
./scripts/config --enable CRYPTO_POLYVAL
./scripts/config --enable CRYPTO_GHASH_CLMUL_NI_INTEL
./scripts/config --enable CRYPTO_SHA512_SSSE3
./scripts/config --enable HID_MULTITOUCH
./scripts/config --enable CRYPTO_SHA256_SSSE3
./scripts/config --enable CRYPTO_SHA1_SSSE3
#./scripts/config --enable NVME_AUTH
./scripts/config --module I2C_HID_ACPI
./scripts/config --module I2C_HID_CORE
./scripts/config --enable SERIO_RAW
./scripts/config --enable PKCS8_PRIVATE_KEY_PARSER
